### ISSUE TITLE
simple for loop

### ISSUE THREAD

**Issue by tcarlsen** [mquandalle/meteor-jade#100]
I cant figure out how to make a for loop work

```jade
- for (var x = 0; x < 3; x++)
  li item
```

I tried these:

```jade
- for (var x = 0; x < 3; x++)
for (var x = 0; x < 3; x++)
for x = 0; x < 3; x++
```

errors:

```
Expected tag name after `<`
...{{for (var x = 0; x < 3; x++)}}}
                        ^

Jade syntax error: Expected tag name after `<`
(var x = 0; x < 3; x++)
               ^

Jade syntax error: Expected tag name after `<`
x = 0; x < 3; x++
          ^
``

**Comment by mquandalle** [comment]
This is not possible to do this in meteor-jade, because the code is not compiled in JavaScript function but in a abstract structure that handle reactivity. For this kind of use case, in both meteor-jade and spacebars, you have to use a template helper:

```jade
template(name="myTemplate")
  ul
    each items
      li this
```

```js
Template.myTemplate.helpers({
  items: function() {
    return ["item1", "item2", "item3"];
  }
});
```

Once again, there is nothing specific to jade here, this is just the way meteor works.
