### ISSUE TITLE
Can this be used with react-meteor?

### ISSUE THREAD

**Issue by trusktr** [mquandalle/meteor-jade#126]
Can this somehow be used with [react-meteor](https://github.com/reactjs/react-meteor) to write Jade syntax instead of HTML syntax for React? Or maybe this project is only meant for Blaze views, and what I want to do is entirely separate?

**Comment by mquandalle** [comment]
meteor-blaze compiles jade templates to blaze views, and therefore it probably can't be reused with the React.js runtime engine. Fortunately there is an “official” jade to react compiler: https://github.com/jadejs/react-jade. I never tried it, but since it's supported by @ForbesLindesay I imagine it is the way to go.

What we may want to have in a meteor, is a `jsx` handler that support ES6 template strings:

```js
render: function() { return jade`#myContent` }
```

**Comment by trusktr** [comment]
Interesting, thanks!

**Comment by sandervanhooft** [comment]
Any experience to share about using Jade + React + Meteor? Did you get it to work somehow?

**Comment by mquandalle** [comment]
Personally, I didn’t try.

**Comment by trusktr** [comment]
I gave up on the idea. I've been using regular JSX. It might be nice though, something like "jadesx".

**Comment by laurentpayot** [comment]
@sandervanhooft you can have a look [here](https://forums.meteor.com/t/resolved-error-using-jade-with-react-in-jsx-react-jade/8177) with 1.2, and [here](https://forums.meteor.com/t/resolved-error-using-jade-with-react-in-jsx-react-jade/8177) with 1.3.
