### ISSUE TITLE
Template cant be named "content"?

### ISSUE THREAD

**Issue by Orbyt** [mquandalle/meteor-jade#145]
Getting a `Jade syntax error: Template can't be named "content" on line 1`.

Was wondering why it doesnt allow templates to be named content?

**Comment by mquandalle** [comment]
So this error isn’t thrown due to a weird side effect of some code, but instead from an explicit condition check — https://github.com/mquandalle/meteor-jade/blob/c25b5e071659c1e0e02124ac8b6de200853a8a1d/packages/jade-compiler/lib/transpilers.js#L108-L109.

To be honest, I can’t think of any good reason for this test, I believe I just recopied it from the early days of Spacebars. Since Spacebars doesn’t deny this name anymore, it’s pretty reasonable to remove this test in meteor-jade.

**Comment by Orbyt** [comment]
added a PR, should we expect an update on the package soon? Or is it automatic?

**Comment by dalgard** [comment]
I've modified a fork of this package, which adds some useful features and also fixes this bug in `0.5.4_1`. The fork has been released as [dalgard:jade](https://github.com/dalgard/meteor-jade).

The new package will be kept in sync with the original, should there be any updates, and generally be maintained until, hopefully, the two packages can be merged.

**Comment by mquandalle** [comment]
This is fixed in `master` thanks to @Orbyt PR.
