### ISSUE TITLE
How to use jade with Meteor v1.3 and it's module way of doing things

### ISSUE THREAD

**Issue by jeremyfourna** [mquandalle/meteor-jade#204]
Hello,

With the Meteor v1.3, how can we continue to use jade with the module **import** way of doing things now ?

Because with Meteor v1.2, you only have to write your `jade` templates and magic occurs everything works, but now, I don't know how to make `jade` work out of the box with Meteor.

Do we have to stay with the atmosphere package ? Do we have to install `jade` from npm ? Do we have to define some code to importe `jade` templates into js files ? Do we have to go back to `html` ?

I didn't find informations about the impact of Meteor v1.3 for jade.

Thanks in advance for your answer, and thanks for your great work with this Meteor package.

Dexterneo

**Comment by mikeifomin** [comment]
@dexterneo Jade with the Meteor 1.3 is ok. See [official meteor guide](http://guide.meteor.com/build-tool.html#blaze-jade)

In the Meteor 1.3 for a better support large apps and  better testing is [recommended](http://guide.meteor.com/structure.html#example-app-structure) to use imports instead of autoimported files.

``` sh
imports/
  # all files are here (jade,coffee,js and so on)

client/
  main.js                      # client entry point, imports all client code

server/
  main.js                      # server entry point, imports all server code
```

About the NPM. Yes the MDG will [move](https://github.com/meteor/meteor/blob/release-1.4/Roadmap.md#full-transition-to-npm) Meteor 'parts' to the NPM in a future. For now you can still use the Atmosphere mquandalle:jade. But **officially** they are not going to deprecate(?) the Atmosphere package system.

### Short answer

So now the right place for jade files is inside imports/ directory. And don't forget to import them in frontend code.

**imports/ui/pages/pageIndex.jade**

``` jade
template(name="pageIndex")
   h1 Hello there!
```

**imports/ui/pages/pageIndex.coffee**

``` coffee
{ Template } = require 'meteor/templating'
require './pageIndex.jade' # Yes "*.jade" files

Template.pageIndex.onCreated ->
    conslole.log('created')





```

**Comment by jeremyfourna** [comment]
OK thanks for you answer, I can now migrate all my apps using `jade` in peace ;)
