### ISSUE TITLE
Calling helper that takes an argument as attribute value

### ISSUE THREAD

**Issue by vojto** [mquandalle/meteor-jade#9]
For example, with Iron Router:

```
a(href=pathFor('foo')) Foo
```

That doesn't work.

**Comment by seeekr** [comment]
Just a heads up. You should totally include this caveat in the docs in the main Readme so people don't have to google the solutions since this is something that people need to do reasonably often!

By the way, what's the status of this project? I might be interested in helping out in getting meteor-jade being as fully featured as the default Spacebars is, but currently there's a bunch of minor issues that would need to be worked out. Like this one, as well as a few other things that I can't recall off the top of my head that came up as I was using meteor-jade for the first time on a project.

**Comment by onstottj** [comment]
+1 for documenting which jade features aren't supported in meteor-jade.  I've spent several hours wondering why things like `class={class1:ifSomethingIsTrue, class2:ifSomethingElseIsTrue}` doesn't work.  Thanks for the great implementation though.
